language: go
sudo: true
go:
  - 1.9
before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -y
  - sudo apt-get install glide -y
install:
  - glide install
  - make test
script:
  - go build -ldflags="-X main.Version=${VERSION}" -o bin/speedtest
  - ./bin/speedtest -p
notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
